### ISSUE TITLE
Log a warning when the user register a null value as localStream (opentera-webrtc-web-client)

### ISSUE THREAD

**Issue by G-Lauz** [introlab/opentera-webrtc#25]
When the user instantiate a new `StreamClient` he can pass a null value in the attribute `localStream` of the `streamConfiguration` parameters of the constructor: 

```javascript
const StreamConfiguration = {
    localStream: nullSrcVideoElement.srcObject, // Where nullSrcVideoElement.srcObject = null
    isSendOnly: false
};
streamClient = new openteraWebrtcWebClient.StreamClient(SignalingServerConfiguration, StreamConfiguration, RtcConfiguration, logger);
```

If the user expect that he had pass a valid value to `localStream` it can be really hard for him to figure it out what's wrong in his code without any warning.

**Comment by doumdi** [comment]
@mamaheux, could we just write a warning message on the console when null is passed as a localStream?

**Comment by mamaheux** [comment]
If the StreamClient doesn't need to send a video stream, localStream should be null or undefined. So, I don't think the warning is a good idea.
