### ISSUE TITLE
ARM64 build with cross compiler

### ISSUE THREAD

**Issue by doumdi** [introlab/opentera-webrtc#41]

**Comment by mamaheux** [comment]
- [ ] Rendre le CMakeLists.txt de WebRTC root
- [ ] Ajouter une option pour cross-compiler ou non dans le CMakeLists.txt de WebRTC
- [ ] Ajouter des Github Actions pour compiler WebRTC sur Ubuntu 18.04 et 20.04 pour AMD64 et ARM64
- [ ] Dans le CMakeLists.txt de 3rdParty, ajouter le téléchargement de WebRTC selon la version d'Ubuntu et le Processeur
- [ ] Corriger la compilation du binding pour python3 sur Ubuntu 18.04.

**Comment by doumdi** [comment]
@mamaheux en bonus on a ARM32. Je crois que tout est terminé.
