### ISSUE TITLE
Pybind11 >2.6.0 blocking

### ISSUE THREAD

**Issue by doumdi** [introlab/opentera-webrtc#42]
- Python tests on version 3.6, 3.8 do not work. 
- FunctionTask<void>::callSync seems to block. We should investigate the underling webrtc thread. Lambda functions are never called.

**Comment by doumdi** [comment]
We reverted to 2.5.0 for now and it seems to work.

**Comment by philippewarren** [comment]
@doumdi Is this fixed? I think this https://github.com/introlab/opentera-webrtc/pull/74/commits/88df6c8bd9c2709b0303207489560b3c02138e81#diff-635bf768ab018c10faed7d317340bc749338fd7ceb751978adb6414d21b23a1d did it.

**Comment by doumdi** [comment]
Yes.
